#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-qtawesome
Version  : 1.2.2
Release  : 51
URL      : https://files.pythonhosted.org/packages/a7/80/02a91c72692d6bf597a8b95bddd692b036207deeb8b55efc362923143a25/QtAwesome-1.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/a7/80/02a91c72692d6bf597a8b95bddd692b036207deeb8b55efc362923143a25/QtAwesome-1.2.2.tar.gz
Summary  : FontAwesome icons in PyQt and PySide applications
Group    : Development/Tools
License  : MIT
Requires: pypi-qtawesome-bin = %{version}-%{release}
Requires: pypi-qtawesome-license = %{version}-%{release}
Requires: pypi-qtawesome-python = %{version}-%{release}
Requires: pypi-qtawesome-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(qtpy)

%description
# QtAwesome
[![license](https://img.shields.io/pypi/l/qtawesome.svg)](./LICENSE)
[![pypi version](https://img.shields.io/pypi/v/qtawesome.svg)](https://pypi.org/project/qtawesome/)
[![conda version](https://img.shields.io/conda/vn/conda-forge/qtawesome.svg)](https://www.anaconda.com/download/)
[![download count](https://img.shields.io/conda/d/conda-forge/qtawesome.svg)](https://www.anaconda.com/download/)
[![OpenCollective Backers](https://opencollective.com/spyder/backers/badge.svg?color=blue)](#backers)
[![Join the chat at https://gitter.im/spyder-ide/public](https://badges.gitter.im/spyder-ide/spyder.svg)](https://gitter.im/spyder-ide/public)<br>
[![PyPI status](https://img.shields.io/pypi/status/qtawesome.svg)](https://github.com/spyder-ide/qtawesome)
[![Github Windows build status](https://github.com/spyder-ide/qtawesome/workflows/Windows%20tests/badge.svg)](https://github.com/spyder-ide/qtawesome/actions)
[![Github Linux build status](https://github.com/spyder-ide/qtawesome/workflows/Linux%20tests/badge.svg)](https://github.com/spyder-ide/qtawesome/actions)
[![Github MacOS build status](https://github.com/spyder-ide/qtawesome/workflows/Macos%20tests/badge.svg)](https://github.com/spyder-ide/qtawesome/actions)
[![Documentation Status](https://readthedocs.org/projects/qtawesome/badge/?version=latest)](https://qtawesome.readthedocs.io/en/latest/?badge=latest)

%package bin
Summary: bin components for the pypi-qtawesome package.
Group: Binaries
Requires: pypi-qtawesome-license = %{version}-%{release}

%description bin
bin components for the pypi-qtawesome package.


%package license
Summary: license components for the pypi-qtawesome package.
Group: Default

%description license
license components for the pypi-qtawesome package.


%package python
Summary: python components for the pypi-qtawesome package.
Group: Default
Requires: pypi-qtawesome-python3 = %{version}-%{release}

%description python
python components for the pypi-qtawesome package.


%package python3
Summary: python3 components for the pypi-qtawesome package.
Group: Default
Requires: python3-core
Provides: pypi(qtawesome)
Requires: pypi(qtpy)

%description python3
python3 components for the pypi-qtawesome package.


%prep
%setup -q -n QtAwesome-1.2.2
cd %{_builddir}/QtAwesome-1.2.2
pushd ..
cp -a QtAwesome-1.2.2 buildavx2
cp -a QtAwesome-1.2.2 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672196685
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-qtawesome
cp %{_builddir}/QtAwesome-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-qtawesome/fb156b859d8f4ca1df7b961447e5760b41dcf055
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qta-browser

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-qtawesome/fb156b859d8f4ca1df7b961447e5760b41dcf055

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
